import "./globals.css";

export const metadata = {
  title: "Next13 Github Api Project",
  description: "Generated by create next app",
  keywords: "esta sección contiene palabras clave para los motores de búsqueda",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
